# Generated by Django 6.1 on 2026-08-26 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ('-updated_at', '-created_at', 'id')},
        ),
    ]
