"""
Django settings for Jaaz project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/

Every value that differs between a laptop and a real deployment is read
from the environment. `server/.env` is loaded here for local development;
in production the same names are expected to be set by the platform, and
no .env file needs to exist. See server/.env.example for the full list.
"""

import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# The repository keeps the Django project one level below server/, so the
# .env sits beside requirements.txt rather than beside manage.py.
load_dotenv(BASE_DIR.parent / '.env')


# ---------------------------------------------------------------------------
# Environment helpers
#
# Deliberately tiny. The point is that a misconfigured deployment fails at
# import time with a clear message, rather than booting and silently signing
# tokens with a development key.
# ---------------------------------------------------------------------------

class ImproperlyConfiguredEnv(RuntimeError):
    pass


def env(name, default=None):
    value = os.environ.get(name)
    return default if value is None or value == '' else value


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None or value == '':
        return default
    return value.strip().lower() in ('1', 'true', 'yes', 'on')


def env_int(name, default):
    value = os.environ.get(name)
    if value is None or value == '':
        return default
    try:
        return int(value)
    except ValueError as exc:
        raise ImproperlyConfiguredEnv(f'{name} must be an integer, got {value!r}') from exc


def env_float(name, default):
    value = os.environ.get(name)
    if value is None or value == '':
        return default
    try:
        return float(value)
    except ValueError as exc:
        raise ImproperlyConfiguredEnv(f'{name} must be a number, got {value!r}') from exc


def env_list(name, default=()):
    value = os.environ.get(name)
    if value is None or value == '':
        return list(default)
    return [item.strip() for item in value.split(',') if item.strip()]


def env_required(name, when):
    """Read a variable that has no safe default outside development."""
    value = env(name)
    if value:
        return value
    if when:
        raise ImproperlyConfiguredEnv(
            f'{name} must be set. Refusing to start without it.'
        )
    return None


DEBUG = env_bool('DJANGO_DEBUG', default=True)


# SECURITY WARNING: keep the secret key used in production secret!
# The insecure literal below is only ever reachable with DEBUG=True.
SECRET_KEY = env('DJANGO_SECRET_KEY') or env_required('DJANGO_SECRET_KEY', when=not DEBUG) or (
    'django-insecure-=kgl5z3h63esrg)-jzh%_0i+spgp%0r2o#fik9l8m-+f&#n^va'
)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Needed for ArrayField, which the knowledge base stores embeddings in.
    'django.contrib.postgres',

    'rest_framework',
    'corsheaders',

    'account',
    'knowledge_base',
    'chat',
    # Loaded by path because the app's directory name collides with
    # django.contrib.admin's app label; AdminPanelConfig relabels it.
    'admin.apps.AdminPanelConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Must sit above CommonMiddleware so preflight OPTIONS requests get a
    # CORS response instead of a redirect.
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Jaaz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Jaaz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('POSTGRES_DB', 'jaaz_db'),
        'USER': env('POSTGRES_USER', 'postgres'),
        'PASSWORD': env('POSTGRES_PASSWORD', ''),
        'HOST': env('POSTGRES_HOST', 'localhost'),
        'PORT': env('POSTGRES_PORT', '5432'),
        'CONN_MAX_AGE': env_int('POSTGRES_CONN_MAX_AGE', 0),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': env_int('PASSWORD_MIN_LENGTH', 12)},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Argon2id first. Django's Argon2PasswordHasher uses the `id` variant, and
# listing it first means existing PBKDF2 hashes in auth_user are transparently
# re-hashed to Argon2id the next time each of those users signs in — the
# remaining entries are kept solely so those old hashes still verify.
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# ---------------------------------------------------------------------------
# Authentication
#
# The access token travels in an HttpOnly cookie, so the browser attaches it
# automatically and no frontend code ever reads it. Everything below is the
# configuration surface for that; the implementation lives in account/.
# ---------------------------------------------------------------------------

# Whether X-Forwarded-For may be believed. Off unless a reverse proxy is
# known to append the real client address and to strip any copy the client
# sent — otherwise a caller can forge the address that per-IP throttling and
# the security log both key on.
TRUST_X_FORWARDED_FOR = env_bool('TRUST_X_FORWARDED_FOR', default=False)

AUTH_JWT = {
    # No fallback to SECRET_KEY: the signing key is what stands between an
    # attacker and a forged admin session, and it should be rotatable
    # independently of Django's SECRET_KEY.
    'SECRET': env('JWT_SECRET') or env_required('JWT_SECRET', when=not DEBUG) or SECRET_KEY,
    'ALGORITHM': 'HS256',
    'ISSUER': env('JWT_ISSUER', 'jaaz.api'),
    'AUDIENCE': env('JWT_AUDIENCE', 'jaaz.console'),
    # Short-lived by design. There is no refresh token: the console is an
    # internal tool, and re-authenticating after a lapse is an acceptable
    # cost for not having to build refresh rotation and revocation.
    'EXPIRES_IN': env_int('JWT_EXPIRES_IN', 60 * 60 * 8),
    # Tolerance for clock drift between the signer and the verifier.
    'LEEWAY': env_int('JWT_LEEWAY', 10),
}

AUTH_COOKIE = {
    'NAME': env('AUTH_COOKIE_NAME', 'jaaz_session'),
    # Defaults to `not DEBUG` so a plain-HTTP laptop works and a deployment
    # has to opt *out* of Secure rather than opt in.
    'SECURE': env_bool('AUTH_COOKIE_SECURE', default=not DEBUG),
    # Lax, because the console and the API are deployed same-site (behind one
    # domain in dev via the Vite proxy, and on sibling hosts in production).
    # 'None' would be required for a genuinely cross-site split, and would
    # then also require Secure.
    'SAMESITE': env('AUTH_COOKIE_SAMESITE', 'Lax'),
    'PATH': env('AUTH_COOKIE_PATH', '/'),
    'DOMAIN': env('AUTH_COOKIE_DOMAIN'),
}

# Brute-force protection that survives a process restart and works across
# workers, because it is stored on the account row rather than in memory.
AUTH_LOCKOUT = {
    'MAX_FAILED_ATTEMPTS': env_int('AUTH_MAX_FAILED_ATTEMPTS', 8),
    'LOCKOUT_SECONDS': env_int('AUTH_LOCKOUT_SECONDS', 15 * 60),
}


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'account.authentication.JWTCookieAuthentication',
    ],
    # Closed by default. Endpoints that must be reachable signed-out
    # (login, the CSRF primer) opt out explicitly with AllowAny.
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'EXCEPTION_HANDLER': 'common.errors.api_exception_handler',
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': env('LOGIN_THROTTLE_RATE', '10/min'),
        'auth-read': env('AUTH_READ_THROTTLE_RATE', '120/min'),
        # Uploads cost disk, CPU and (with a paid provider) money per call.
        'kb-upload': env('KB_UPLOAD_THROTTLE_RATE', '30/min'),
        'kb-write': env('KB_WRITE_THROTTLE_RATE', '60/min'),
        'kb-read': env('KB_READ_THROTTLE_RATE', '240/min'),
        # Every search is an embedding call to the provider.
        'kb-search': env('KB_SEARCH_THROTTLE_RATE', '60/min'),
        # Every chat turn is a retrieval plus a completion — the most
        # expensive request this application serves.
        'chat-write': env('CHAT_WRITE_THROTTLE_RATE', '20/min'),
        'chat-read': env('CHAT_READ_THROTTLE_RATE', '120/min'),
    },
    'UNAUTHENTICATED_USER': None,
}

if not DEBUG:
    # The browsable API renders user-controlled data into HTML and is a
    # debugging affordance, not a product surface.
    REST_FRAMEWORK['DEFAULT_RENDERER_CLASSES'] = [
        'rest_framework.renderers.JSONRenderer',
    ]


# ---------------------------------------------------------------------------
# CSRF and CORS
#
# Cookie auth means the browser attaches credentials to cross-site requests
# it is allowed to make, so HttpOnly alone does not stop CSRF. The scheme
# here is double-submit: Django sets a readable `csrftoken` cookie, the
# frontend echoes it in `X-CSRFToken`, and account.authentication enforces
# the match on every unsafe request.
# ---------------------------------------------------------------------------

# Must stay readable by JavaScript — the frontend has to copy it into the
# header. This is not the session token; leaking it achieves nothing on its
# own because an attacker's origin still cannot read the victim's copy.
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = env_bool('CSRF_COOKIE_SECURE', default=not DEBUG)
CSRF_COOKIE_SAMESITE = env('CSRF_COOKIE_SAMESITE', 'Lax')
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS')

SESSION_COOKIE_SECURE = env_bool('SESSION_COOKIE_SECURE', default=not DEBUG)
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = env('SESSION_COOKIE_SAMESITE', 'Lax')

# Empty by default: local development proxies /api through Vite, so requests
# are same-origin and no CORS headers are needed at all. Only a deployment
# that serves the console from a different origin needs to fill this in.
CORS_ALLOWED_ORIGINS = env_list('CORS_ALLOWED_ORIGINS')
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = [
    'accept',
    'content-type',
    'origin',
    'x-csrftoken',
    'x-requested-with',
]


# ---------------------------------------------------------------------------
# Transport security
#
# These only take effect behind real HTTPS. Left off in DEBUG so a laptop on
# http://localhost is not redirected into a scheme it cannot serve.
# ---------------------------------------------------------------------------

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', default=True)
    SECURE_HSTS_SECONDS = env_int('SECURE_HSTS_SECONDS', 60 * 60 * 24 * 365)
    SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool('SECURE_HSTS_INCLUDE_SUBDOMAINS', default=True)
    SECURE_HSTS_PRELOAD = env_bool('SECURE_HSTS_PRELOAD', default=False)
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = 'same-origin'
    X_FRAME_OPTIONS = 'DENY'

    # Only enable when a reverse proxy is known to set this header and to
    # strip any client-supplied copy of it. Trusting it otherwise lets a
    # client claim HTTPS over plain HTTP.
    if env_bool('TRUST_X_FORWARDED_PROTO', default=False):
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


# ---------------------------------------------------------------------------
# Knowledge base
#
# Uploaded documents, the chunks extracted from them, and the embeddings that
# make those chunks retrievable. Every number here is configuration rather
# than a literal in the pipeline, because the right values depend on the
# embedding model in use and will change when the model does.
# ---------------------------------------------------------------------------

# Where uploaded documents live. A dedicated storage alias rather than
# `default`, so nothing else in the project can accidentally write into the
# knowledge base's bucket — and so switching to S3 is this block plus
# django-storages, with no code change anywhere else.
KNOWLEDGE_BASE_STORAGE_ALIAS = 'knowledge_base'

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
    },
    KNOWLEDGE_BASE_STORAGE_ALIAS: {
        'BACKEND': env(
            'KB_STORAGE_BACKEND', 'django.core.files.storage.FileSystemStorage'
        ),
        'OPTIONS': {
            'location': env('KB_STORAGE_ROOT', str(BASE_DIR.parent / 'media')),
            # No base_url. These files are never addressable over HTTP: the
            # web server does not serve this directory, and nothing hands out
            # a link to it. An uploaded file is input, not content.
            'base_url': None,
        },
    },
}

KNOWLEDGE_BASE = {
    # -- Upload limits --------------------------------------------------
    # 20 MB. Large enough for a real product manual, small enough that a
    # single request cannot occupy a worker for minutes.
    'MAX_DOCUMENT_SIZE': env_int('MAX_DOCUMENT_SIZE', 20 * 1024 * 1024),
    'MIN_DOCUMENT_SIZE': env_int('MIN_DOCUMENT_SIZE', 1),

    # -- Chunking -------------------------------------------------------
    # Characters, not tokens: counting tokens exactly needs the model's own
    # tokeniser, and a character budget with a 4:1 estimate is both adequate
    # and provider-independent. ~1200 chars ≈ 300 tokens, which leaves room
    # to put several chunks in an LLM context alongside a question.
    'CHUNK_SIZE': env_int('RAG_CHUNK_SIZE', 1200),
    # Overlap keeps a sentence that straddles a boundary retrievable from
    # either side. Roughly one paragraph's worth.
    'CHUNK_OVERLAP': env_int('RAG_CHUNK_OVERLAP', 200),
    # Below this a chunk carries too little context to be worth retrieving;
    # trailing fragments are merged backwards instead.
    'MIN_CHUNK_SIZE': env_int('RAG_MIN_CHUNK_SIZE', 120),
    # A hard ceiling for text with no paragraph or sentence breaks to split
    # on, so one pathological input cannot produce a single enormous chunk.
    'MAX_CHUNK_SIZE': env_int('RAG_MAX_CHUNK_SIZE', 2400),

    # -- Embeddings -----------------------------------------------------
    # 'hashing' is a deterministic local provider: no key, no network, no
    # cost. It makes the whole pipeline runnable and testable out of the box.
    # It is NOT semantic — set EMBEDDING_PROVIDER=openai for real retrieval.
    'EMBEDDING_PROVIDER': env('EMBEDDING_PROVIDER', 'hashing'),
    'EMBEDDING_MODEL': env('EMBEDDING_MODEL', ''),
    # Server-side only. Never rendered, never returned by an endpoint, never
    # given a VITE_ prefix.
    'EMBEDDING_API_KEY': env('EMBEDDING_API_KEY'),
    'EMBEDDING_API_BASE': env('EMBEDDING_API_BASE', 'https://api.openai.com/v1'),
    'EMBEDDING_DIMENSIONS': env_int('EMBEDDING_DIMENSIONS', 0) or None,
    'EMBEDDING_BATCH_SIZE': env_int('EMBEDDING_BATCH_SIZE', 64),
    'EMBEDDING_TIMEOUT': env_int('EMBEDDING_TIMEOUT', 30),
    'EMBEDDING_MAX_RETRIES': env_int('EMBEDDING_MAX_RETRIES', 3),

    # -- Vector store ---------------------------------------------------
    'VECTOR_STORE': env('RAG_VECTOR_STORE', 'postgres'),
    'SEARCH_TOP_K': env_int('RAG_SEARCH_TOP_K', 5),
    'SEARCH_MAX_TOP_K': env_int('RAG_SEARCH_MAX_TOP_K', 25),
    'SEARCH_MIN_SCORE': env_float('RAG_SEARCH_MIN_SCORE', 0.0),

    # -- Processing -----------------------------------------------------
    # eager  → run inline in the request (tests; never production)
    # thread → run on a background thread (single-process development)
    # worker → leave it queued for `manage.py process_documents`
    'TASK_DISPATCH': env('RAG_TASK_DISPATCH', 'thread' if DEBUG else 'worker'),
    'WORKER_POLL_SECONDS': env_int('RAG_WORKER_POLL_SECONDS', 5),
    # A document stuck mid-ingest for longer than this is assumed to belong
    # to a worker that died, and is returned to the queue.
    'STALE_PROCESSING_MINUTES': env_int('RAG_STALE_PROCESSING_MINUTES', 15),
    'MAX_PROCESSING_ATTEMPTS': env_int('RAG_MAX_PROCESSING_ATTEMPTS', 5),
}


# ---------------------------------------------------------------------------
# AI service
#
# The RAG service: BGE embeddings, Qdrant, hybrid retrieval, reranking, and
# the language models. Django never holds a Qdrant credential or an LLM key —
# it holds one shared token for this service, and this service holds the rest.
#
# The browser never reaches it either. Chat requests go to Django, which
# authenticates the user from the session cookie and forwards the question
# with the user's identity attached.
# ---------------------------------------------------------------------------

AI_SERVICE = {
    'URL': env('AI_SERVICE_URL', 'http://127.0.0.1:8001'),
    # Must match SECURITY__SERVICE_TOKEN in ai_service. Required in
    # production for the same reason it is there: network placement is not
    # access control.
    'TOKEN': env('AI_SERVICE_TOKEN') or env_required(
        'AI_SERVICE_TOKEN', when=not DEBUG
    ) or '',
    # One tenant today. Every Qdrant query is filtered by it, so adding a
    # second is a data change rather than an audit of every query.
    'TENANT_ID': env('AI_SERVICE_TENANT_ID', 'default'),
    'TIMEOUT_SECONDS': env_int('AI_SERVICE_TIMEOUT_SECONDS', 30),
    # Indexing embeds every chunk of a document. Called from a worker, where
    # a long wait costs nobody anything.
    'INDEX_TIMEOUT_SECONDS': env_int('AI_SERVICE_INDEX_TIMEOUT_SECONDS', 300),
    # Streaming answers are long-lived by nature; this bounds a stuck one.
    'STREAM_TIMEOUT_SECONDS': env_int('AI_SERVICE_STREAM_TIMEOUT_SECONDS', 180),
}

CHAT = {
    # Turns sent to the AI service. It applies its own ceiling as well; this
    # one stops Django serialising a thousand-message conversation first.
    'MAX_HISTORY_MESSAGES': env_int('CHAT_MAX_HISTORY_MESSAGES', 12),
    'MAX_MESSAGE_CHARACTERS': env_int('CHAT_MAX_MESSAGE_CHARACTERS', 4000),
    'MAX_CONVERSATIONS_PER_USER': env_int('CHAT_MAX_CONVERSATIONS_PER_USER', 200),
}


# ---------------------------------------------------------------------------
# Logging
#
# `jaaz.security` carries the authentication audit trail: who signed in, who
# failed, from where. It never receives a password or a token.
#
# `jaaz.knowledge_base` carries the ingestion trail: which document reached
# which stage, how long it took, why it failed. It records counts and
# identifiers — never document contents, and never the embedding API key.
# ---------------------------------------------------------------------------

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'security': {
            'format': '[{asctime}] {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'security',
        },
    },
    'loggers': {
        'jaaz.security': {
            'handlers': ['console'],
            'level': env('SECURITY_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'jaaz.knowledge_base': {
            'handlers': ['console'],
            'level': env('KNOWLEDGE_BASE_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        'jaaz.chat': {
            'handlers': ['console'],
            'level': env('CHAT_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
    },
}
